README.md
The project image has moved to Docker Hub.
Any reference to the Docker image should be updated.
=> 📝 Update the Docker image reference

.github/PULL_REQUEST_TEMPLATE/performance_improvement.md, CONTRIBUTING.md, README.md
Correct typos in documentation
N/A
=> 📝 Documentation typos

Dockerfile, etc/nginx/includes/logs.conf, etc/nginx/nginx.conf
Switch log format in nginx.conf : from default nginx log format to json output in stdout.
=> 💻 Update log format from default nginx to json

edge/src/assets/AssetSpec.ts, edge/test/assets/AssetNameParser.test.ts
=> 🐛 Capture namespace from URL

html/a7_browse_body.html
=> :sparkles: Use natural sorting order of assets in directory listings

README.md
Fixed and simplified docker documentation.
=> :memo: Fix docker documentation

html/a7_browse_body.html
Make the box header sticky for a better user experience on smaller screens.
=> :sparkles: Sticky header

html/a7_browse_asset.html, html/a7_browse_body.html
- :bug: Fix API documentation activation
- :sparkles: Auto-enable WebIDE for swagger files
=> :bug: Fix API documentation activation

html/a7_browse_body.html, html/a7_browse_directory.html
- Auto-upgrade trilogy design system to the latest `1.x` version
- Migrate to the assets.bytel service
- Small visual revamp:
| before | after |
|-|-|
| ![](https://user-images.githubusercontent.com/44078/185596384-3db378cf-3957-467e-93db-63c8214e857c.png) | ![](https://user-images.githubusercontent.com/44078/185596003-3f7a18f3-dad9-4973-ac4c-c33e18ff4622.png) |
=> :arrow_up: Upgrade trilogy and use the assets.bytel service

Dockerfile
=> :arrow_up: Upgrade nginx to 1.22.0

html/a7_browse_body.html
- 🐛 Make action buttons visible
- 💄 Nicer looking breadcrumbs
- 🐛 Enhanced failed search behavior
=> :bug: Make action buttons visible + Nicer looking breadcrumbs + Enhanced failed search behavior

edge/src/actions/respondWithCatalog.ts
For a given catalog with two referened assets:
```json
[
{
"name": "foo/bar@1.2.03",
"name": "foo/bar@1.2.4"
}
]
```
The first is semver-compliant, the second is not.
The current implementation of the catalog responds with a 404 ; the new implementation rather ignores malformed assets.
With the previous example, the catalog would respond with:
```json
{
"assets": [
{
"path": "/foo/bar@1.2.4",
"data": {
"minor": 2,
"name": "foo",
"valid": true,
"namespace": "",
"subname": "foo",
"patch": 4,
"major": 1,
"latest": true,
"version": "1.2.4"
}
}
]
}
```
=> :bug: Ignore malformed assets in catalog

etc/nginx/includes/zip_directories.conf, scripts/generate-directories-metadata.sh, test/performance/generate-directories-metadata.sh
- 🐛 Fix zip directories download
- ⚡ Metadata generation: now executed in parallel
- ⚡ Metadata generation: no without the actual file size
=> Metadata files script optimizations

etc/nginx/includes/browse_directories.conf
=> Fix cache browsing

etc/nginx/includes/cache_expiration.conf, test/integration/run.sh, test/integration/tests/cache_expiration.http
=> return 60sec max-age for 302 so akamai can cache them

edge/src/assets/AssetComparator.ts, edge/src/helpers/String.ts
=> :bug: Fix releases comparison

README.md, edge/src/actions/expand.ts, etc/nginx/nginx.conf
=> Add debug headers + More fine-grained cache + Fix CORS regression

edge/src/actions/expand.ts, edge/src/actions/respondWithAssetMeta.ts, edge/src/actions/respondWithCatalog.ts, test/integration/compose.common.yml, test/integration/compose.yml, test/integration/tests/cache_expiration.http, test/integration/tests/restrict_http_methods.http
=> :bug: Fix expansion bugs and have more tests to pass

edge/src/actions/expand.ts, edge/test/actions/expand.test.ts
=> :white_check_mark: Passing unit tests

edge/src/assets/AssetSpec.ts, edge/test/assets/AssetNameParser.test.ts
=> :bug: Handle hyphens in build spec

.github/workflows/docker-image-build-mr.yml, .github/workflows/testing.yml, .gitignore, compose.yml, test/integration/compose.common.yml, test/integration/run.sh, test/integration/tests/meta_queries.http, test/integration/tests/search.http, test/integration/tests/smart_routing.http
=> integrate-integ-tests

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, edge/src/assets/AssetNameParser.ts, edge/src/assets/AssetPredicate.ts, edge/src/tests/assets/AssetPredicate.test.ts, edge/vite.config.mjs, test/integration/compose.common.yml, test/integration/run.sh, test/integration/tests/search.http, test/integration/tests/smart_routing.http
=> :bug: fix failed integration tests

html/a7_browse_asset.html
Replacement of Rapidoc by Redoc.
I hope none.
Creation of the HTML file manually to verify the correct functioning of the Redoc implementation
Replacement of Rapidoc by Redoc.
=> ✨ Change rapidoc for redoc

html/a7_browse_directory.html
Display download link
Before:
After:
=> 🐛 display download link

html/a7_browse_directory.html
=> 🐛 display all folder when package has several versions
